# taken from https://github.com/koalaman/shellcheck/wiki/TravisCI
language: bash

# Use container-based infrastructure for quicker build start-up
sudo: false

before_install:
  - apt-get remove binutils

addons:
  apt:
    sources:
    - debian-sid    # Grab shellcheck from the Debian repo (o_O)
    packages:
    - shellcheck

script:
 - shellcheck *.sh

matrix:
  fast_finish: true
