#!/usr/bin/env bash

set -e

ROOT_DIR="$(dirname "$0")"
cd "$ROOT_DIR"
ROOT_DIR=$(pwd)

source lib.sh

# these have to happen after the PKI is generated by ./startup-jars.sh
cd "$ROOT_DIR/verify-eidas-trust-anchor"
echo "Generating trust-anchor..."
# generate the trust-anchor
git checkout master
set_build_number
fixup_repos "$@"
./gradlew clean build >/dev/null #2&>/dev/null
apt-get install xxd

grep entityId ../verify-local-startup/data/stub-fed-config/countries/*yml | cut -d ' ' -f 2 | while IFS= read -r COUNTRY_ENTITY_ID; do
echo "caching metadata for $COUNTRY_ENTITY_ID"
AGGREGATOR_FILE_NAME=$(echo -n "$COUNTRY_ENTITY_ID" | xxd -ps -c1000)
java -jar "./build/libs/verify-eidas-trust-anchor-1.0-$BUILD_NUMBER.jar" import -o "$AGGREGATOR_FILE_NAME.jwk" "$COUNTRY_ENTITY_ID" ../verify-local-startup/data/pki/stub_idp_signing_primary.crt ../verify-local-startup/data/ca-certificates/dev-idp-ca.pem.test ../verify-local-startup/data/ca-certificates/dev-root-ca.pem.test
# cache the proxied metadata from stub-country that for the eidas aggregator
# this is served from the stub metadata server and initially retrieved from stub-country
# when it is running
# cache the servicemetadata for stub-country to be accessed via the aggregator
CURLCOUNT=10
while [ $CURLCOUNT -gt 0 ]; do
  curl -o "$AGGREGATOR_FILE_NAME" "$COUNTRY_ENTITY_ID" >/dev/null 2&>/dev/null || EXIT_CODE=$? && true
  if [ $EXIT_CODE -eq 7 ] || [ $EXIT_CODE -eq 0 ]; then
    # curl is exiting with code 7 even though it downloads ok
    break
  fi
  sleep 1s
  echo -n "."
  CURLCOUNT=$((CURLCOUNT-1))
done
mkdir -p ../verify-local-startup/data/metadata/aggregator
cp "$AGGREGATOR_FILE_NAME" ../verify-local-startup/data/metadata/aggregator/
done

echo "generating trust anchor..."
# build a trust anchor that only contains stub-country, and is signed by our metadata signing key
java -jar "./build/libs/verify-eidas-trust-anchor-1.0-$BUILD_NUMBER.jar" sign-with-file ./*.jwk --cert=../verify-local-startup/data/pki/metadata_signing_a.crt --key=../verify-local-startup/data/pki/metadata_signing_a.pk8 -o trust-anchor
cp trust-anchor ../verify-local-startup/data/metadata/

